# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQB0ppQoAZ2J6oXY7-JU4Rv5EFWq0hB2
"""

import streamlit as st
import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt

# Title
st.title("📈 Prophet Forecast with Regressors (Exchange Rate)")

# File uploader
uploaded_file = st.file_uploader("Upload Monthly Exchange Rate CSV", type=['csv'])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.subheader("Preview of Uploaded Data")
    st.write(df.head())

    # Select datetime and target
    date_col = st.selectbox("Select Date Column", df.columns)
    y_col = st.selectbox("Select Exchange Rate Column", [col for col in df.columns if col != date_col])

    # Rename for Prophet
    df_prophet = df.rename(columns={date_col: 'ds', y_col: 'y'})

    # Identify regressors
    regressor_cols = [col for col in df_prophet.columns if col not in ['ds', 'y']]

    # Initialize and add regressors
    model = Prophet()
    for col in regressor_cols:
        model.add_regressor(col)

    # Fit model
    model.fit(df_prophet)

    # Predict future
    num_months = st.slider("Months to Predict", 1, 24, 12)
    future = model.make_future_dataframe(periods=num_months, freq='MS')

    for col in regressor_cols:
        future[col] = None
        past_mask = future['ds'].isin(df_prophet['ds'])
        future.loc[past_mask, col] = df_prophet.set_index('ds').loc[future.loc[past_mask, 'ds'], col].values
        future[col].fillna(df_prophet[col].iloc[-1], inplace=True)

    # Forecast
    forecast = model.predict(future)

    # Output
    st.subheader("Forecasted Exchange Rate")
    st.dataframe(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(num_months))

    # Plot
    st.subheader("📊 Forecast Plot")
    fig1 = model.plot(forecast)
    st.pyplot(fig1)

    st.subheader("🔍 Forecast Components")
    fig2 = model.plot_components(forecast)
    st.pyplot(fig2)